source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.6', '>= 6.1.6.1'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# 下記追加 --------------------------------------
# 環境変数を読み込む
gem 'dotenv-rails'
# 環境毎の設定管理（環境変数の管理）を行う。dotenv-railsの後に入れないとエラーになる。
gem 'config'
gem 'devise'
gem 'devise_token_auth'
# 「アイ・ワン・エイト・エヌ」と読みます。これは「国際化（Internationalization）」の略語
gem 'rails-i18n'
# Deviseで使用される様々なメッセージやエラー文を翻訳する
gem 'devise-i18n'
# Deviseのビューファイル（ログインフォームやパスワードリセットフォームなど）を翻訳する。
gem 'devise-i18n-views'
gem 'kaminari' # ページネーション
gem 'active_storage_validations' # active_starageのバリデーション設定
# [アクティブストレージのバリアントを使用する]
# 'image_processing'は'mini_magick'も一緒にインストールする
gem 'image_processing', '~> 1.2'
# ランダムな値を生成するgemで,メールアドレス、人名、パスワードなどのランダムな値を生成してくれます。
gem 'faker'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # 下記追加 --------------------------------------
  # RSpecをインストール
  gem 'rspec-rails'
  # テスト用のgem、FactoryBotをインストール。
  gem 'factory_bot_rails'
  # binding.pryでステップ実行できるようにする
  gem 'pry-byebug'
  gem "pry-doc"
  # pry-railsをインストールすると、pryも一緒にインストールされます。
  gem 'pry-rails'
  # [Can't escape from eval with next]エラーの解消
  gem 'pry-nav'
  # 開発環境でメール送信をテストする
  gem "letter_opener_web"
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # 下記追加 --------------------------------------
  # rubocop:コード解析・検査ツール。
  gem 'rubocop', require: false
  # RuboCopで入れた方がいい機能。Rubyのパフォーマンスを改善するためのチェックを追加。
  gem "rubocop-performance", require: false
  # Railsのベストプラクティスに従うようにコードをチェック
  gem "rubocop-rails", require: false
  # RSpecのテストコードに対するコードをチェック
  gem "rubocop-rspec", require: false
  # Rubyのコード補完、ドキュメントを提供してくれるライブラリ
  gem "solargraph"
end

# 下記追加 --------------------------------------
group :test do
  # RSpec内で使用できるライブラリで、複雑なテストをワンライナーで書くことができるマッチャ
  gem 'shoulda-matchers'
end

group :production do
  # productionモード（S3）向けのビルドの時のみ、S3関連 gem を追加でインストール
  # https://github.com/rails/rails/blob/v6.1.4.6/activestorage/lib/active_storage/service/s3_service.rb#L3
  gem "aws-sdk-s3"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
