# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
# [例えば lib/tasks/capistrano.rake のように、.rake で終わる lib/tasks にあるファイルに独自のタスクを追加すると、
#   自動的に Rake で利用できるようになります。]

require_relative "config/application"

Rails.application.load_tasks
