# 1 next.jsの3001番からのリクエストを受け入れ
front_domain: http://localhost:3001

# @          @@          @@          @@          @@          @@          @@          @@          @
# gem 'config'の、
# rails g config:install によって作成された、定数管理ファイル
# ------------------------------------------------------------------------------------------------
# アプリケーションが動作している環境に応じて、
# 開発環境: development.yml
# テスト環境: test.yml
# 本番環境: production.yml
# の設定ファイルを切り替えて参照してくれます。
# ------------------------------------------------------------------------------------------------
# フロントのnext.jsのurlを記載
# この値は、Settings.front_domainという形で取り出すことができます。