# 1
front_domain: https://horror-domo-app.com

# @          @@          @@          @@          @@          @@          @@          @@          @
# 1
# .front_domain: https://horror-domo-app.com/（末尾に/を付ける）だとエラー。
# - production.yml`設定ファイルの`https://horror-domo-app.com/`から末尾のスラッシュを削除して
# `https://horror-domo-app.com`にすることで、CORSポリシーの実施におけるオリジンの正確なマッチング方法のため、
# CORSエラーが解決した。
# ------------------------------------------------------------------------------------------------
# . 1. **完全一致要件**
# - CORSポリシーは、`Origin`ヘッダーでブラウザから送信されたオリジンと、サーバーのCORS設定で許可されたオリジンとの
# 完全一致を要求する。オリジンはURIとして照合され、スキーム（`http`または`https`）、ホスト名、ポートは同一でなけれ
# ばならない。末尾のスラッシュはオリジンではなくパスの一部とみなされますが、その有無によってオリジンの解釈や保存方法に
# 不一致が生じる可能性があります。
# - フロントからにリクエストは`https://horror-domo-app.com`なので、このバックエンド側の許可オリジンを
# `https://horror-domo-app.com/`にすると失敗する
# ------------------------------------------------------------------------------------------------
# . 要約
# - サーバー構成の許可されるオリジンから末尾のスラッシュを削除することで、ブラウザから送信されたオリジンとサーバーが期
# 待するオリジンとの不一致が修正され、CORSエラーが解決され、クロスオリジンリクエストが正常に処理されるようになった。
